<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <AssemblyName>Xornet</AssemblyName>
    <RootNamespace>Xornet</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SharpPcap" Version="6.3.0" />
    <PackageReference Include="PacketDotNet" Version="1.4.7" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
